services:
  dummy-problems:
    container_name: dummy-problems
    tty: true
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.gitconfig:/home/ubuntu/.gitconfig
      - ../:/home/ubuntu/dummy-problems
      - data:/home/ubuntu/data
    # runtime: nvidia
    shm_size: '64gb'

volumes:
  data: